### ISSUE TITLE
About data & pre-trained models

### ISSUE THREAD

**Issue by ouchaochao** [Tencent/MedicalNet#19]
请问有微云版的数据和预训练的模型下载吗? 

翻墙表示太慢了 T .T

**Comment by FCYtheFreeman** [comment]
翻墙确实很慢，发一个国内的网盘呗

**Comment by cshwhale** [comment]
@ouchaochao @FCYtheFreeman 
You can download the data & pre-trained models from Tencent Weiyun: https://share.weiyun.com/55sZyIx

**Comment by FCYtheFreeman** [comment]
> @ouchaochao @FCYtheFreeman
> You can download the data & pre-trained models from Tencent Weiyun: https://share.weiyun.com/55sZyIx

thx a lot :-)

**Comment by ouchaochao** [comment]
> @ouchaochao @FCYtheFreeman
> You can download the data & pre-trained models from Tencent Weiyun: https://share.weiyun.com/55sZyIx

比心
 ♥
