### ISSUE TITLE
Could it be used to classifition task?

### ISSUE THREAD

**Issue by A-kali** [Tencent/MedicalNet#37]
The pretrained model looks like an complete segmentation model, could it be used to classifition task? If it could, how should I change the code?

**Comment by dwang-sflscientific** [comment]
Hey @A-kali, did you find the classification model implementation?

**Comment by A-kali** [comment]
> Hey @A-kali, did you find the classification model implementation?

yeah, I remove the upsample layers and add a fc_layer

**Comment by dwang-sflscientific** [comment]
Thanks @A-kali ! Really appreciated your help!

**Comment by 123liluky** [comment]
@A-kali @dwang-sflscientific  Did you get pleased classification results? How about the classification accuracy.

**Comment by dwang-sflscientific** [comment]
I used it for an image-wise regression task. The performance is competitive.

**Comment by lovemmmax** [comment]
> > Hey @A-kali, did you find the classification model implementation?
> 
> yeah, I remove the upsample layers and add a fc_layer
Hey, I just started learning. Could you  share the code of classification task training?

**Comment by A-kali** [comment]
Give me your email address and I'll send you the code
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lovemmmax"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月25日(星期一) 晚上9:43
收件人:&nbsp;"Tencent/MedicalNet"<MedicalNet@noreply.github.com&gt;;
抄送:&nbsp;"Hsaki"<2509660158@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Tencent/MedicalNet] Could it be used to classifition task? (#37)





   
Hey @A-kali, did you find the classification model implementation?
  
re the c
yeah, I remove the upsample layers and add a fc_layer
Hey, I just started learning. Could you sha

ode of classification task training?

**Comment by lovemmmax** [comment]
> Give me your email address and I'll send you the code ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"lovemmmax"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月25日(星期一) 晚上9:43 收件人:&nbsp;"Tencent/MedicalNet"<MedicalNet@noreply.github.com&gt;; 抄送:&nbsp;"Hsaki"<2509660158@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [Tencent/MedicalNet] Could it be used to classifition task? (#37) Hey @A-kali, did you find the classification model implementation? re the c yeah, I remove the upsample layers and add a fc_layer Hey, I just started learning. Could you sha ode of classification task training? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you! My email is 734800253@qq.com

**Comment by hajra90** [comment]
hello @A-kali can you please share the classification code with me as well. I shall be thankful.

**Comment by zeeshannisar** [comment]
> Give me your email address and I'll send you the code ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"lovemmmax"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月25日(星期一) 晚上9:43 收件人:&nbsp;"Tencent/MedicalNet"<MedicalNet@noreply.github.com&gt;; 抄送:&nbsp;"Hsaki"<2509660158@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [Tencent/MedicalNet] Could it be used to classifition task? (#37) Hey @A-kali, did you find the classification model implementation? re the c yeah, I remove the upsample layers and add a fc_layer Hey, I just started learning. Could you sha ode of classification task training? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Hello @A-kali 
Can you please share the classification code with me? My email is zshnnisar@gmail.com.

**Comment by A-kali** [comment]
> hello @A-kali can you please share the classification code with me as well. I shall be thankful.

How can I contact you?

**Comment by hajra90** [comment]
> > hello @A-kali can you please share the classification code with me as well. I shall be thankful.
> 
> How can I contact you?

at hajra.arif90@gmail.com
thanks

**Comment by A-kali** [comment]
> > Give me your email address and I'll send you the code ------------------ 原始邮件 ------------------ 发件人: "lovemmmax"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年5月25日(星期一) 晚上9:43 收件人: "Tencent/MedicalNet"<[MedicalNet@noreply.github.com](mailto:MedicalNet@noreply.github.com)>; 抄送: "Hsaki"<[2509660158@qq.com](mailto:2509660158@qq.com)>;"Mention"<[mention@noreply.github.com](mailto:mention@noreply.github.com)>; 主题: Re: [Tencent/MedicalNet] Could it be used to classifition task? (#37) Hey @A-kali, did you find the classification model implementation? re the c yeah, I remove the upsample layers and add a fc_layer Hey, I just started learning. Could you sha ode of classification task training? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> Hello @A-kali
> Can you please share the classification code with me? My email is [zshnnisar@gmail.com](mailto:zshnnisar@gmail.com).

I have sent the file to you, but it failed

**Comment by Margherita96** [comment]
> Give me your email address and I'll send you the code ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"lovemmmax"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月25日(星期一) 晚上9:43 收件人:&nbsp;"Tencent/MedicalNet"<MedicalNet@noreply.github.com&gt;; 抄送:&nbsp;"Hsaki"<2509660158@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [Tencent/MedicalNet] Could it be used to classifition task? (#37) Hey @A-kali, did you find the classification model implementation? re the c yeah, I remove the upsample layers and add a fc_layer Hey, I just started learning. Could you sha ode of classification task training? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Hello @A-kali,
Could you send me the classification code? I would be very grateful. My email is margherita.butti@mail.polimi.it

**Comment by Irises1** [comment]
> > > Give me your email address and I'll send you the code ------------------ 原始邮件 ------------------ 发件人: "lovemmmax"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年5月25日(星期一) 晚上9:43 收件人: "Tencent/MedicalNet"<[MedicalNet@noreply.github.com](mailto:MedicalNet@noreply.github.com)>; 抄送: "Hsaki"<[2509660158@qq.com](mailto:2509660158@qq.com)>;"Mention"<[mention@noreply.github.com](mailto:mention@noreply.github.com)>; 主题: Re: [Tencent/MedicalNet] Could it be used to classifition task? (#37) Hey @A-kali, did you find the classification model implementation? re the c yeah, I remove the upsample layers and add a fc_layer Hey, I just started learning. Could you sha ode of classification task training? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > Hello @A-kali
> > Can you please share the classification code with me? My email is [zshnnisar@gmail.com](mailto:zshnnisar@gmail.com).
> 
> I have sent the file to you, but it failed. I will try resending it.

Can you share the classification code, thank you very much, my email:yuan2325@aliyun.com

**Comment by NAMZseng** [comment]
> Give me your email address and I'll send you the code ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"lovemmmax"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月25日(星期一) 晚上9:43 收件人:&nbsp;"Tencent/MedicalNet"<MedicalNet@noreply.github.com&gt;; 抄送:&nbsp;"Hsaki"<2509660158@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [Tencent/MedicalNet] Could it be used to classifition task? (#37) Hey @A-kali, did you find the classification model implementation? re the c yeah, I remove the upsample layers and add a fc_layer Hey, I just started learning. Could you sha ode of classification task training? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.



> Give me your email address and I'll send you the code ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"lovemmmax"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月25日(星期一) 晚上9:43 收件人:&nbsp;"Tencent/MedicalNet"<MedicalNet@noreply.github.com&gt;; 抄送:&nbsp;"Hsaki"<2509660158@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [Tencent/MedicalNet] Could it be used to classifition task? (#37) Hey @A-kali, did you find the classification model implementation? re the c yeah, I remove the upsample layers and add a fc_layer Hey, I just started learning. Could you sha ode of classification task training? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi @A-kali Could you please send me the classification code? Appreciate it! My email is : nanrong_z@foxmail.com

**Comment by zsddd** [comment]
> > > 给我你的电子邮件地址，我会把原始邮件------------------代码发给你，------------------发件人：“lovemmmax”<[notifications@github.com](mailto:notifications@github.com)>;发送时间： 2020年5月25日（星期一） 晚上9：43 收件人： “腾讯/MedicalNet”<[MedicalNet@noreply.github.com](mailto:MedicalNet@noreply.github.com)>;抄送： “Hsaki”<[2509660158@qq.com](mailto:2509660158@qq.com)>;”提及“<[mention@noreply.github.com](mailto:mention@noreply.github.com)>;主题： 回复： [腾讯/MedicalNet] 它可以用来分类任务吗？（#37）嘿@A-kali，你找到分类模型实现了吗？是的，我删除了上采样图层并添加了一个fc_layer 嘿，我刚刚开始学习。你能对分类任务培训进行颂歌吗？- 你收到这个是因为你被提及。直接回复此电子邮件、在 GitHub 上查看或取消订阅。
> > 
> > 
> > 你好@A-kali你能和我分享分类代码吗？我的电子邮件[已 zshnnisar@gmail.com](mailto:zshnnisar@gmail.com)。
> 
> 我已将文件发送给您，但失败了。我会尝试重新发送它。



> > 嘿@A-kali，你找到分类模型实现了吗？
> 
> 是的，我删除了上采样图层并添加了fc_layer

可以发下代码吗，大大？非常感谢 1017621789@qq.com

**Comment by lander1003** [comment]
> Give me your email address and I'll send you the code ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"lovemmmax"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月25日(星期一) 晚上9:43 收件人:&nbsp;"Tencent/MedicalNet"<MedicalNet@noreply.github.com&gt;; 抄送:&nbsp;"Hsaki"<2509660158@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [Tencent/MedicalNet] Could it be used to classifition task? (#37) Hey @A-kali, did you find the classification model implementation? re the c yeah, I remove the upsample layers and add a fc_layer Hey, I just started learning. Could you sha ode of classification task training? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi @A-kali Could you please send me the classification code? Appreciate it! My email is : [nanrong_z@foxmail.com](lander@bupt.edu.cn) Thank you !!!

**Comment by Hogandr** [comment]
Hey @A-kali 
can you also share the code with me? 
halamprecht1@gmx.net
thanks in advance

**Comment by neeleshbisht99** [comment]
Hi, Can anyone please share the code with me as well ? 
Here: neeleshbisht99@gmail.com 
@zeeshannisar  @hajra90 @A-kali

**Comment by Hogandr** [comment]
Hi @neeleshbisht99 ,
if you get an reply can you forward the code to me?

**Comment by RenXiaoman** [comment]
Hi @A-kali Could you please send me the classification code? Appreciate it! My email is : [jenhsiaoman@163.com]Thank you !!!
