### ISSUE TITLE
Some minor typos in the paper...

### ISSUE THREAD

**Issue by Eurus-Holmes** [Tencent/MedicalNet#4]
Hi, thanks for your awesome work!
But there are some minor typos in the paper...

- In Section3.3,

<img width="1308" alt="屏幕快照 2019-07-29 16 19 51" src="https://user-images.githubusercontent.com/34226570/62079440-bc549900-b21c-11e9-981d-bfb424d270d0.png">

_**It should be "except"...**_

- In Section4.1,

<img width="1316" alt="屏幕快照 2019-07-29 16 21 41" src="https://user-images.githubusercontent.com/34226570/62079556-fd4cad80-b21c-11e9-9edb-ed635d7b6d1d.png">

_**It should be "Fig.4"...**_

- In Section4.2,

<img width="1327" alt="屏幕快照 2019-07-29 16 23 07" src="https://user-images.githubusercontent.com/34226570/62079654-2bca8880-b21d-11e9-9ee0-86b918416adf.png">

<img width="1332" alt="屏幕快照 2019-07-29 16 23 35" src="https://user-images.githubusercontent.com/34226570/62079690-3be26800-b21d-11e9-8c4f-811a77edd0da.png">

_**There are some repeated sentences...**_

**Comment by cshwhale** [comment]
We appreciate your helpful suggestions and all the typos, grammar mistakes will be addressed in the new version. Thank you again.
