### ISSUE TITLE
Can you provide the pretrained model?

### ISSUE THREAD

**Issue by weiziyoung** [Tencent/MedicalNet#7]
Can you provide the pretrained model so that we don't need to train from scratch.

**Comment by cshwhale** [comment]
The pre-trained models can be downloaded from
https://drive.google.com/file/d/1N8U1EImXmXwt0fL6PsULU3oYTBzC45jm/view?usp=sharing

And you can find this url in the second step of "Demo" part.

**Comment by weiziyoung** [comment]
Cheers.

On Aug 2, 2019, at 2:16 PM, Sihong Chen <notifications@github.com<mailto:notifications@github.com>> wrote:


The pre-trained models can be downloaded from
https://drive.google.com/file/d/1N8U1EImXmXwt0fL6PsULU3oYTBzC45jm/view?usp=sharing<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdrive.google.com%2Ffile%2Fd%2F1N8U1EImXmXwt0fL6PsULU3oYTBzC45jm%2Fview%3Fusp%3Dsharing&data=01%7C01%7Czw1y18%40soton.ac.uk%7C1cc4841da0b64b6cb68608d7174ba42d%7C4a5378f929f44d3ebe89669d03ada9d8%7C0&sdata=Wfznnn6vfguFDaFyCdojvmaKAxPONq0AhhP1f9Ub6j8%3D&reserved=0>

And you can find this url in the second step of "Demo" part.
