### ISSUE TITLE
Assertion is always true, perhaps remove parentheses?

### ISSUE THREAD

**Issue by cclauss** [Tencent/MedicalNet#8]
flake8 testing of https://github.com/Tencent/MedicalNet on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./datasets/brains18.py:58:13: F631 assertion is always true, perhaps remove parentheses?
            assert(img_array.shape ==  mask_array.shape, "img shape:{} is not equal to mask shape:{}".format(img_array.shape, mask_array.shape))
            ^
1     F631 assertion is always true, perhaps remove parentheses?
1
```

**Comment by weiziyoung** [comment]
I agree with you. For this assertion, the parenthese is redundant and can make the assertion fail.

**Comment by cshwhale** [comment]
@cclauss 
Thanks for your friendly reminder, we have fixed the bug.
