### ISSUE TITLE
Maybe an error in the code?

### ISSUE THREAD

**Issue by JiYuanFeng** [Tencent/MedicalNet#9]
![image](https://user-images.githubusercontent.com/20653249/62627161-69d15600-b95b-11e9-9913-b5cc70d4c6dd.png)

Hi, I use your dataloader to load the BrainS18 dataset, and I found that maybe an error ?  as shown above, the input data's shape is H*W*D,  but the resize scale is computed by D*H*W ?

**Comment by back2yes** [comment]
There are other bugs in the code.

For example, this is the code for saving the model:
```
torch.save({
                        'ecpoch': epoch,
                        'batch_id': batch_id,
                        'state_dict': model.state_dict(),
                        'optimeizer': optimizer.state_dict()},
                        model_save_path)
```

However when loading the model it became like this:
`model.load_state_dict(checkpoint['net_state_dict'])`

The keywords for saving and loading are not consistent: `net_state_dict` and `state_dict`, `'optimeizer'` (typo in the code) and `optimizer_state_dict`.

I don't think you can reproduce any meaningful result from these codes.

**Comment by cshwhale** [comment]
@JiYuanFeng 
Hi, we transposed the data from WHD format to DHW format.
Thanks for your friendly reminder, we have fixed the bug.

**Comment by cshwhale** [comment]
@back2yes 
Thank you for your reminder, we have corrected the typo.
